### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by AlexKoeppelSigSci** [signaturescience/nrc#8]
In table describing outputs: 

rraa | 2 | Count of RA to AA mismatches

should read : 

rraa | 2 | Count of RR to AA mismatches

**Comment by AlexKoeppelSigSci** [comment]
Tried to push a fix myself, but lack permission.

**Comment by vpnagraj** [comment]
thanks @AlexKoeppelSigSci ! 

i believe we have the repo set up so that only certain folks can push directly to main. not 100% sure if you would be able to push to a new branch on this repo. but what *should* work is forking => submitting a PR from your fork.

i can also add you to the list of collaborators on this directly if need be.

**Comment by AlexKoeppelSigSci** [comment]
@vpnagraj I was trying to push to a separate branch, not main.  I'll try out the forking option.

**Comment by vpnagraj** [comment]
fixed in #9
